### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/bun#2]
- [ ] Rework hooks. Leave only BeforeScan and AfterScan. The rest will be replaced with hooks that accept queries so the following should be possible

````
func (u *User) BeforeCreateTableQuery(ctx context.Context, q *CreateTableQuery) error {
    if q.GetDB().Dialect().Name() == dialect.SQLite {
        // do something
    }
    return nil
}

func (u *User) AfterCreateTableQuery(ctx context.Context, q *CreateTableQuery) error {
    _, err := q.GetDB().NewCreateIndex().Foo().Bar().Exec()
    return err
}
````

- [ ] Add CreateIndex and DropIndex queries
- [ ] Port migrations
- [ ] Add AutoMigrate
- [ ] Possibly add YAML fixtures
- [ ] Provide a starter kit that integrates everything together
